package test.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import test.greendao.bean.User;
import test.greendao.bean.Door;
import test.greendao.bean.UserDoor;

import test.greendao.dao.UserDao;
import test.greendao.dao.DoorDao;
import test.greendao.dao.UserDoorDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig doorDaoConfig;
    private final DaoConfig userDoorDaoConfig;

    private final UserDao userDao;
    private final DoorDao doorDao;
    private final UserDoorDao userDoorDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        doorDaoConfig = daoConfigMap.get(DoorDao.class).clone();
        doorDaoConfig.initIdentityScope(type);

        userDoorDaoConfig = daoConfigMap.get(UserDoorDao.class).clone();
        userDoorDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        doorDao = new DoorDao(doorDaoConfig, this);
        userDoorDao = new UserDoorDao(userDoorDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Door.class, doorDao);
        registerDao(UserDoor.class, userDoorDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        doorDaoConfig.getIdentityScope().clear();
        userDoorDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public DoorDao getDoorDao() {
        return doorDao;
    }

    public UserDoorDao getUserDoorDao() {
        return userDoorDao;
    }

}
